#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Stop the ' +
                                 'containerized versions of TwinePM ' +
                                 'services.')

parser.add_argument('--branch', '-b', action='store_true', default='dev',
                    help='use the master branch', nargs=1)

args = parser.parse_args()

prefix = 'twine-package-manager'
repo_names = ['client', 'diskdb', 'logic', 'memorydb', 'scripts', 'web']
repos = []
for name in repo_names:
    repos.append('{}-{}'.format(prefix, name))

base_cmd = ['git', 'clone', '-b']
for index, repo in enumerate(repos):
    file_path = dirname + repo_names[index]
    cmd = list(base_cmd)
    cmd.extend([branch_name, args.branch])

    proc = subprocess.Popen(cmd)
    proc.communicate()

print('Subrepositories cloned.')