version: '3'

services:
  web:
    build:
      context: web/
    depends_on:
      - logic
    environment: &mode
      TWINEPM_MODE: development
    networks:
      - backend_web
    ports:
      - '80:8000'

  logic:
    build:
      context: logic/
    depends_on:
      - diskdb
      - memorydb
    environment: *mode
    networks:
      - backend_web
      - backend_persistence

  diskdb:
    build:
      context: diskdb/
    environment: *mode
    networks:
      - backend_persistence

  memorydb:
    build:
      context: memorydb/
    environment: *mode
    networks:
      - backend_persistence

  client:
    build:
      context: client/
    environment: *mode
    networks:
      - frontend
    ports:
      - '80:8080'

networks:
  backend_web:
    driver: bridge
  backend_persistence:
    driver: bridge
  frontend:
    driver: bridge