version: '3'

services:
  web:
    build:
      dockerfile: web/Dockerfile
    depends_on:
      - logic
    environment: &mode
      TWINEPM_MODE: development
    networks:
      - backend_web
    ports:
      - '443:80'

  logic:
    build:
      dockerfile: logic/Dockerfile
    depends_on:
      - diskdb
      - memorydb
    environment: *mode
    networks:
      - backend_web
      - backend_persistence

  diskdb:
    build:
      dockerfile: diskdb/Dockerfile
    environment: *mode
    networks:
      - backend_persistence

  memorydb:
    build: 
      dockerfile: memorydb/Dockerfile
    environment: *mode
    networks:
      - backend_persistence

  client:
    build:
      dockerfile: client/Dockerfile
    environment: *mode
    networks:
      - frontend

networks:
  backend_web:
    driver: bridge
  backend_persistence:
    driver: bridge
  frontend:
    driver: bridge