#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')

parser = argparse.ArgumentParser(description='Rebuild containerized ' +
                                 'versions of TwinePM services.')

args = parser.parse_args()

cmd = [os.path.join(dirname, 'stopVm')]
proc = subprocess.Popen(cmd)
proc.communicate()

cmd = [os.path.join(dirname, 'runVm', '--provision')]
proc = subprocess.Popen(cmd)
proc.communicate()