#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Rebuild containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--force', '-f', action='store_true', default=None,
                    help='don\'t ask for confirmation')

args = parser.parse_args()

cmd = [os.path.join(dirname, 'destroyVm')]
if args.force:
    cmd.append('--force')

proc = subprocess.Popen(cmd)
proc.communicate()

cmd = [os.path.join(dirname, 'buildVm')]
proc = subprocess.Popen(cmd)
proc.communicate()